### PR TITLE
Add support for running 2019 Worst Evictors sql code 

### PR DESCRIPTION
**Pull request by sraby**
This PR adds a command for re-running our sql code to generate the raw data for the 2019 Worst Evictors list. It also renames a bunch of files and commands to make the distinction between 2018 and 2019 more clear. Hopefully, too, this will allow us to add handling for future years more easily!

### CODE REVIEW

**Comment by sraby** [comment]
@toolness Check this out! I updated our requirements to pull in the most recent PyPi release of nycdb, but as I said, it seems there are two datasets that were introduced to nycdb on github after the latest pypi release. When trying to build the db, I'll get two specific errors: ```KeyError: 'rentstab_18'``` and ```KeyError: 'marshal_evictions_19'```, which are two of the more recent datasets added to nycdb. I’ve been able to test that the new command actually works by reverting those two datasets in the SQL code to older datasets, which allows us to build the db with no issues. But of course, in order for the results of our SQL queries to be accurate we need to be able to pull in these two new datasets.

Seems like we need to either update the PyPi project or (more sustainably) pull from nycdb's latest github instead of PyPi here? Would love your guidance on what's easiest.

**Comment by toolness** [comment]
Ok I just pushed two commits... One of them makes us use the latest version of nycdb from github, while the other makes it possible to do everything in Docker (my computer now has Python 3.8, which one of nycdb's dependencies doesn't seem to be compatible with, so it's easiest for me to just use Docker for everything).

Anyways, the thing is, I'm still getting `KeyError: 'rentstab_18'` but I think that's because the dataset for the 2018 rentstab data is actually called `rentstab_v2`?

Regardless, if you re-install your pip dependencies now, I think you should hopefully get the latest version of nycdb... 🤞

**Comment by sraby** [comment]
Nice @toolness, thank you for that! The new docker setup is so great. I fixed the misnaming of the `rentstab_v2` dataset and I also reconfigured the data imports so we now pull all of the marshal evictions data directly from nycdb instead of importing each as a monkeypatched dataset.

One quick thing: for some reason the import of `pluto_19v1` in the builddb process gets "killed" after stalling for a few seconds. There is no error message but this is what gets logged:
```
Table pluto_19v1 not found in the database. Downloading...
Loading pluto_19v1 into the database...
0rows [00:00, ?rows/s]Killed
```
Has this happened to you? I'm wondering if it has something to do with my dying computer... maybe it can't handle such a bit task?

**Comment by toolness** [comment]
Ah yeah that happened to me too!  I was confused, but it definitely isn't just your dying computer--I will look into it!

**Comment by sraby** [comment]
Oh weird! Yeah, it doesn't actually cause any errors when running the scripts, but when you check the CSV output for the 2019 data, any field coming from PLUTO shows up as all 0's.

**Comment by toolness** [comment]
Ah it looks like the Docker VM wasn't being given enough memory, so the kernel was killing the Python process when it was using too much.  I just documented how to increase the memory in 
2a8b368.

Also, make sure you add/remove appropriate entries for new data directory files to/from the git repository/`.gitignore`.  After running `worst.py` it's saying that one CSV in there has been modified, and it's complaining about some other CSVs in there not being tracked by git...

**Comment by sraby** [comment]
Right right, ok sounds good. Thanks for the flag, @toolness!

**Comment by sraby** [comment]
ok @toolness this should be all good to go now :) thanks again

**Pull request merged**
